### PR TITLE
Use ffmpeg-full extension

### PR DESCRIPTION
**Pull request by Erick555**
This adds support for heif/heic format

### CODE REVIEW

**Comment by tsdgeos** [comment]
No it does not

Can you explain why you think this should make it work?

Our heif image loader has all the dependencies it needs already in the regular runtime as far as i can see

$ ldd ./usr/lib/plugins/imageformats/kimg_heif.so
        linux-vdso.so.1 (0x000075c3f75b3000)
        libQt6Gui.so.6 => /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6 (0x000075c3f6a00000)
        libQt6Core.so.6 => /usr/lib/x86_64-linux-gnu/libQt6Core.so.6 (0x000075c3f6200000)
        libheif.so.1 => /usr/lib/x86_64-linux-gnu/libheif.so.1 (0x000075c3f7484000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x000075c3f5e00000)
        libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x000075c3f5c01000)
        libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x000075c3f7470000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x000075c3f7420000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x000075c3f68b4000)
        libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x000075c3f60b0000)
        libQt6DBus.so.6 => /usr/lib/x86_64-linux-gnu/libQt6DBus.so.6 (0x000075c3f5b2d000)
        libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x000075c3f73d5000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x000075c3f5afa000)
        libOpenGL.so.0 => /usr/lib/x86_64-linux-gnu/libOpenGL.so.0 (0x000075c3f5acd000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x000075c3f5a94000)
        libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x000075c3f5976000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x000075c3f58b0000)
        libz.so.1 => /usr/lib/x86_64-linux-gnu/libz.so.1 (0x000075c3f5896000)
        libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x000075c3f57a7000)
        libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000075c3f5779000)
        libicui18n.so.75 => /usr/lib/x86_64-linux-gnu/libicui18n.so.75 (0x000075c3f5200000)
        libicuuc.so.75 => /usr/lib/x86_64-linux-gnu/libicuuc.so.75 (0x000075c3f4e00000)
        libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x000075c3f56b0000)
        libpcre2-16.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0 (0x000075c3f561c000)
        /lib64/ld-linux-x86-64.so.2 (0x000075c3f75b5000)
        libdav1d.so.7 => /usr/lib/x86_64-linux-gnu/libdav1d.so.7 (0x000075c3f4c1c000)
        libaom.so.3 => /usr/lib/x86_64-linux-gnu/libaom.so.3 (0x000075c3f4600000)
        libSvtAv1Enc.so.2 => /usr/lib/x86_64-linux-gnu/libSvtAv1Enc.so.2 (0x000075c3f3e00000)
        libjpeg.so.62 => /usr/lib/x86_64-linux-gnu/libjpeg.so.62 (0x000075c3f515e000)
        libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x000075c3f50f7000)
        libsharpyuv.so.0 => /usr/lib/x86_64-linux-gnu/libsharpyuv.so.0 (0x000075c3f68ab000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x000075c3f503f000)
        libexpat.so.1 => /usr/lib/x86_64-linux-gnu/libexpat.so.1 (0x000075c3f55f0000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x000075c3f55c4000)
        libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x000075c3f4b7b000)
        libdbus-1.so.3 => /usr/lib/x86_64-linux-gnu/libdbus-1.so.3 (0x000075c3f45a6000)
        libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x000075c3f4583000)
        libbz2.so.1 => /usr/lib/x86_64-linux-gnu/libbz2.so.1 (0x000075c3f609c000)
        libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x000075c3f5031000)
        libicudata.so.75 => /usr/lib/x86_64-linux-gnu/libicudata.so.75 (0x000075c3f2000000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x000075c3f68a1000)
        libsystemd.so.0 => /usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x000075c3f4485000)
        libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x000075c3f4462000)
        libcap.so.2 => /usr/lib/x86_64-linux-gnu/libcap.so.2 (0x000075c3f55b7000)

**Comment by Erick555** [comment]
libheif is in runtime but its plugins live under ffmpeg-full extension

**Comment by Erick555** [comment]
You have `org.freedesktop.Platform.ffmpeg-full//24.08` installed while testing this, right? We need to debug at which point it breaks.

**Comment by Erick555** [comment]
I installed the test build above, had org.freedesktop.Platform.ffmpeg-full//24.08 installed already then downloaded heic file [sample](https://filesamples.com/formats/heic) and opened it through kolorpaint successfully. Can you confirm if those steps work for you?

**Comment by tsdgeos** [comment]
No i did not, indeed adding it works.

Why was it not pulled?

**Comment by Erick555** [comment]
I don't remember if autodownload of extensions is default on or off. I can force it on.

**Comment by Erick555** [comment]
Hm, it still doesn't autodownload the extension. Maybe it can't work from test build?

**Comment by tsdgeos** [comment]
Let's give others some time to comment on autodownload, i don't see why we wouldnot want it but just in case.

**Pull request merged**
